module.exports = [{ 
		"image": "/images/swiper/dungeons2.jpg",
		"tagline": "NEW RELEASES",
		"name": "Dungeons",
		"name2": "And Dragons",
		"imdb_score": "5.4",
		"year": "2020",
		"quality": "4K",
		"quality2": "ULTRA HD",
		"tags": "Romance, Action",
		"description": "'The Football' follows Dee Dee Allen and Barry Glickman Great American",
		"description2": "who are New York City stage stars.",
		"playbutton": "WATCH TRAILER",
		"id": 1
	},{ 
		"image": "/images/swiper/loveagain.png",
		"tagline": "NEW RELEASES",
		"name": "Love",
		"name2": "Again",
		"imdb_score": "5.4",
		"year": "2018",
		"quality": "1080P",
		"quality2": "HD",
		"tags": "Romance, Action",
		"description": "'The Football' follows Dee Dee Allen and Barry Glickman",
		"description2": "who are New York City stage stars.",
		"playbutton": "PLAY BUTTON",
		"id": 2
	},{ 
		"image": "/images/swiper/unicornwarriors.png",
		"tagline": "NEW RELEASES",
		"name": "Unicorn",
		"name2": "Warriors",
		"imdb_score": "5.4",
		"year": "2018",
		"quality": "1080P",
		"quality2": "HD",
		"tags": "Romance, Action",
		"description": "'The Football' follows Dee Dee Allen and Barry Glickman",
		"description2": "who are New York City stage stars.",
		"playbutton": "PLAY BUTTON",
		"id": 3
	},{ 
		"image": "/images/swiper/johnwick4.png",
		"tagline": "NEW RELEASES",
		"name": "John Wick",
		"name2": "Chapter 4",
		"imdb_score": "5.4",
		"year": "2020",
		"quality": "720P",
		"quality2": "HD",
		"tags": "Romance, Action",
		"description": "'The Football' follows Dee Dee Allen and Barry Glickman",
		"description2": "who are New York City stage stars.",
		"playbutton": "WATCH TRAILER",
		"id": 4
	},		
];
